build:
  version: "2.0"

accounts:
  message: "Welcome to Bank accounts related QA APIs "
  contactDetails:
    name: "QA Lead"
    email: "qa@bank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371
