build:
  version: "2.0"
cards:
  message: "Welcome to Bank loans related QA APIs"
  contactDetails:
    name: "Bob QA Lead"
    email: "bob@bank.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467
