build:
  version: "1.0"
cards:
  message: "Welcome to Bank cards related prod APIs"
  contactDetails:
    name: "Smith - Product Owner"
    email: "smith@bank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956