build:
  version: "3.0"

cards:
  message: "Welcome to Bank loans related local APIs "
  contactDetails:
    name: "c# dev - Developer"
    email: "dev@bank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934
